# Tensors in Pytorch

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [102]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


### Creating a tensor

In [103]:
# using empty
a=torch.empty(2,3)
a

tensor([[3.5343e-04, 0.0000e+00, 4.3338e+27],
        [4.4452e-41, 8.9683e-44, 0.0000e+00]])

In [104]:
# check type
type(a)

torch.Tensor

In [105]:
# using zeros
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [106]:
# using ones
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [107]:
# using rand
torch.rand(2,3)

tensor([[0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051]])

In [108]:
# use of seed with rand
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [109]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [110]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [111]:
# other ways

# using arange
print("Using arange ->", torch.arange(0, 10))

# using linspace
print("Using linspace ->", torch.linspace(0, 10, 10))

# using eye
print("Using eye ->", torch.eye(5))

# using full
print("Using eye ->", torch.full((3, 3), 5))

Using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using eye -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [112]:
x=torch.tensor([[1, 2, 3], [4,5,6], [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
x.shape

torch.Size([3, 3])

In [114]:
torch.empty_like(x)

tensor([[        0, 973350016,         0],
        [        0,         1,         1],
        [        0,         0,         0]])

In [115]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [116]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [117]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

## Tensor Data Types

In [118]:
x.dtype

torch.int64

In [119]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [120]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [121]:
y=torch.tensor([1.0, 2.0, 3.0])
print(y)
print(y.dtype)
y.to(torch.int32)

tensor([1., 2., 3.])
torch.float32


tensor([1, 2, 3], dtype=torch.int32)

# Mathematical Operations
## 1. Scalar Operation

In [122]:
x=torch.rand(2,2)
x

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [123]:
# Addition
x+2

tensor([[2.9014, 2.9969],
        [2.7565, 2.2239]])

In [124]:
# Multiplication
x*2

tensor([[1.8028, 1.9938],
        [1.5130, 0.4478]])

In [125]:
# Subtraction
x-2

tensor([[-1.0986, -1.0031],
        [-1.2435, -1.7761]])

In [126]:
# Division
x/2

tensor([[0.4507, 0.4984],
        [0.3783, 0.1119]])

In [127]:
# Modulus
x%2

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [128]:
# Integer division
(x*100)//3

tensor([[30., 33.],
        [25.,  7.]])

In [129]:
((x*100)//3)%2

tensor([[0., 1.],
        [1., 1.]])

In [130]:
# Power
x**2

tensor([[0.8125, 0.9938],
        [0.5723, 0.0501]])

## Element wise operation

In [131]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440]])
tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277]])


In [132]:
a+b

tensor([[1.2502, 0.9229, 1.3130],
        [0.7983, 1.6774, 0.9717]])

In [133]:
a-b

tensor([[-0.6455, -0.5661,  0.3346],
        [ 0.3132,  0.2767, -0.0837]])

In [134]:
a*b

tensor([[0.2866, 0.1328, 0.4030],
        [0.1348, 0.6842, 0.2343]])

In [135]:
a//b

tensor([[0., 0., 1.],
        [2., 1., 0.]])

In [136]:
a%b

tensor([[0.3023, 0.1784, 0.3346],
        [0.0706, 0.2767, 0.4440]])

In [137]:
a**b

tensor([[0.3218, 0.2771, 0.9096],
        [0.8672, 0.9839, 0.6515]])

In [138]:
c=torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [139]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [140]:
# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [141]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [142]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [143]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [144]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [145]:
# clamp
torch.clamp(d, min=2, max=5)

tensor([2.0000, 2.3000, 3.7000, 4.4000])

## Reduction Operation

In [146]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 0., 9.],
        [5., 7., 3.]])

In [147]:
# sum
torch.sum(e)

tensor(24.)

In [148]:
# sum column wise
torch.sum(e, dim=0)

tensor([ 5.,  7., 12.])

In [149]:
# sum row wise
torch.sum(e, dim=1)

tensor([ 9., 15.])

In [150]:
# mean
torch.mean(e)

tensor(4.)

In [151]:
# mean alomng column
torch.mean(e, dim=0)

tensor([2.5000, 3.5000, 6.0000])

In [152]:
# mean alomng row
torch.mean(e, dim=1)

tensor([3., 5.])

In [153]:
# median
torch.median(e)

tensor(3.)

In [154]:
# max
torch.max(e)

tensor(9.)

In [155]:
# min
torch.min(e)

tensor(0.)

In [156]:
# product
torch.prod(e)

tensor(0.)

In [157]:
# standard deviation
torch.std(e)

tensor(3.6878)

In [158]:
# variance
torch.var(e)

tensor(13.6000)

In [159]:
# argmin
torch.argmin(e)

tensor(0)

In [160]:
# argmax
torch.argmax(e)

tensor(2)

In [161]:
z=torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.argmax(z)

tensor(8)

## Matrix Operation

In [165]:
f= torch.randint(size=(2,3), low=0, high=10)
g= torch.randint(size=(3,2), low=0, high=10)

In [166]:
print(f)
print(g)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8],
        [3, 6],
        [1, 5]])


In [169]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 93, 159],
        [ 39,  87]])

In [170]:
vector1=torch.tensor([2,3])
vector2=torch.tensor([3,4])

In [171]:
# dot product
torch.dot(vector1, vector2)

tensor(18)

In [174]:
# transpose
torch.transpose(f,0,1)

tensor([[9, 2],
        [7, 6],
        [9, 7]])

In [175]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 0., 4.],
        [3., 8., 8.],
        [3., 3., 5.]])

In [176]:
# determinant
torch.det(h)

tensor(20.)

In [177]:
# inverse
torch.inverse(h)

tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

In [179]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[2, 9, 5],
        [0, 4, 2]])
tensor([[7, 1, 1],
        [5, 4, 4]])


In [180]:
# greater than
i>j

tensor([[False,  True,  True],
        [False, False, False]])

In [181]:
# less than
i<j

tensor([[ True, False, False],
        [ True, False,  True]])

In [182]:
# equal to
i==j

tensor([[False, False, False],
        [False,  True, False]])

In [183]:
# not equal to
i != j

tensor([[ True,  True,  True],
        [ True, False,  True]])

In [184]:
i >= j

tensor([[False,  True,  True],
        [False,  True, False]])

In [185]:
i<=j

tensor([[ True, False, False],
        [ True,  True,  True]])

## Special Function

In [194]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 6., 1.],
        [4., 5., 6.]])

In [195]:
# log
torch.log(k)

tensor([[1.6094, 1.7918, 0.0000],
        [1.3863, 1.6094, 1.7918]])

In [196]:
# exp
torch.exp(k)

tensor([[148.4132, 403.4288,   2.7183],
        [ 54.5981, 148.4132, 403.4288]])

In [197]:
# square root
torch.sqrt(k)

tensor([[2.2361, 2.4495, 1.0000],
        [2.0000, 2.2361, 2.4495]])

In [198]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9975, 0.7311],
        [0.9820, 0.9933, 0.9975]])

In [200]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.7311, 0.0067],
        [0.2689, 0.2689, 0.9933]])

In [201]:
# relu
torch.relu(k)

tensor([[5., 6., 1.],
        [4., 5., 6.]])

## Inplace Operation

In [203]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])


In [204]:
m+n

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [205]:
m.add_(n)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [206]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [207]:
n

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [208]:
torch.relu(m)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [210]:
m.relu_()

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [212]:
m.sigmoid_()

tensor([[0.7103, 0.7959, 0.8426],
        [0.8279, 0.6396, 0.8073]])

## Copying a tensor

In [213]:
a = torch.rand(2,3)
a

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [214]:
b=a

In [215]:
b

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [216]:
a[0][0]

tensor(0.3904)

In [217]:
a[0][0] = 0

In [218]:
a

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [219]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [220]:
id(a)

136245359132048

In [221]:
id(b)

136245359132048

In [222]:
b=a.clone()

In [223]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [224]:
id(a)

136245359132048

In [225]:
id(b)

136245353818752

In [226]:
a[0][0] = 10

In [227]:
a

tensor([[10.0000,  0.2499,  0.3206],
        [ 0.9753,  0.7582,  0.6688]])

In [228]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [229]:
id(a)

136245359132048

In [230]:
id(b)

136245353818752

## Tensor operation on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.6022, 0.2733, 0.3467],
        [0.4495, 0.3122, 0.9195]], device='cuda:0')

In [7]:
# moving an existing tensor to GPU
a=torch.rand((2,3))
a

tensor([[0.4682, 0.6694, 0.2813],
        [0.9676, 0.1511, 0.2104]])

In [9]:
b=a.to(device)
b

tensor([[0.4682, 0.6694, 0.2813],
        [0.9676, 0.1511, 0.2104]], device='cuda:0')

In [10]:
b + 5

tensor([[5.4682, 5.6694, 5.2813],
        [5.9676, 5.1511, 5.2104]], device='cuda:0')

In [11]:
import time
import torch

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):",cpu_time/gpu_time)

Time on CPU: 16.7592 seconds
Time on GPU: 0.7612 seconds

Speedup (CPU time / GPU time): 22.016844666367234


## Reshaping Tensors

In [12]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [15]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
b=torch.rand(2,3,4)
b

tensor([[[0.9969, 0.0375, 0.1309, 0.4089],
         [0.7413, 0.2446, 0.8786, 0.5355],
         [0.2400, 0.4582, 0.7735, 0.1435]],

        [[0.1812, 0.0790, 0.2702, 0.1609],
         [0.9547, 0.9134, 0.7682, 0.4443],
         [0.6756, 0.6781, 0.7753, 0.7156]]])

In [17]:
# permute
b.permute(2,0,1)

tensor([[[0.9969, 0.7413, 0.2400],
         [0.1812, 0.9547, 0.6756]],

        [[0.0375, 0.2446, 0.4582],
         [0.0790, 0.9134, 0.6781]],

        [[0.1309, 0.8786, 0.7735],
         [0.2702, 0.7682, 0.7753]],

        [[0.4089, 0.5355, 0.1435],
         [0.1609, 0.4443, 0.7156]]])

In [18]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [20]:
# unsqueeze
# image size
c=torch.rand(22,226,3)
c.unsqueeze(0).shape

torch.Size([1, 22, 226, 3])

In [21]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [22]:
import numpy as np

In [23]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [24]:
b = a.numpy()
b

array([1, 2, 3])

In [25]:
type(b)

numpy.ndarray

In [26]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [27]:
torch.from_numpy(c)

tensor([1, 2, 3])